[server]
local="127.0.0.1"
host= "192.168.1.101"
port= "10690"
metricsport= "10691"
name="donself"
healthInterval="5s"
deregister="60s"
zipkinReporter="http://www.rennbon.online:9411/api/v2/spans"
local=true
certFile="/justdo/bc/donself/config/testdata/server.pem"
keyFile="/justdo/bc/donself/config/testdata/server.key"



[consul]
address="127.0.0.1:8500"
scheme= "http"
datacenter=""
user= ""
password=""
waittime= "60s"

[consul.tls]
address="127.0.0.1:8500"
cafile="/justdo/bc/donself/config/testdata/ca.crt"
capath="/justdo/bc/donself/config/testdata/ca.dir"
certfile="/justdo/bc/donself/config/testdata/server.crt"
keyfile="/justdo/bc/donself/config/testdata/sever.key"
enable=false

