// Code generated by protoc-gen-go. DO NOT EDIT.
// source: doneself.protobuf

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AllMyTargetsRequest struct {
	PageIndex            uint32   `protobuf:"varint,1,opt,name=page_index,json=pageIndex,proto3" json:"page_index,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllMyTargetsRequest) Reset()         { *m = AllMyTargetsRequest{} }
func (m *AllMyTargetsRequest) String() string { return proto.CompactTextString(m) }
func (*AllMyTargetsRequest) ProtoMessage()    {}
func (*AllMyTargetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a854b94b567af670, []int{0}
}

func (m *AllMyTargetsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllMyTargetsRequest.Unmarshal(m, b)
}
func (m *AllMyTargetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllMyTargetsRequest.Marshal(b, m, deterministic)
}
func (m *AllMyTargetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllMyTargetsRequest.Merge(m, src)
}
func (m *AllMyTargetsRequest) XXX_Size() int {
	return xxx_messageInfo_AllMyTargetsRequest.Size(m)
}
func (m *AllMyTargetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AllMyTargetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AllMyTargetsRequest proto.InternalMessageInfo

func (m *AllMyTargetsRequest) GetPageIndex() uint32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *AllMyTargetsRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type AllMyTargetsResponse struct {
	Targets              []*Target `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AllMyTargetsResponse) Reset()         { *m = AllMyTargetsResponse{} }
func (m *AllMyTargetsResponse) String() string { return proto.CompactTextString(m) }
func (*AllMyTargetsResponse) ProtoMessage()    {}
func (*AllMyTargetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a854b94b567af670, []int{1}
}

func (m *AllMyTargetsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllMyTargetsResponse.Unmarshal(m, b)
}
func (m *AllMyTargetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllMyTargetsResponse.Marshal(b, m, deterministic)
}
func (m *AllMyTargetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllMyTargetsResponse.Merge(m, src)
}
func (m *AllMyTargetsResponse) XXX_Size() int {
	return xxx_messageInfo_AllMyTargetsResponse.Size(m)
}
func (m *AllMyTargetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AllMyTargetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AllMyTargetsResponse proto.InternalMessageInfo

func (m *AllMyTargetsResponse) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type Target struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Score                uint32   `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	Symbol               string   `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_a854b94b567af670, []int{2}
}

func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (m *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(m, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Target) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Target) GetScore() uint32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Target) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterType((*AllMyTargetsRequest)(nil), "pb.AllMyTargetsRequest")
	proto.RegisterType((*AllMyTargetsResponse)(nil), "pb.AllMyTargetsResponse")
	proto.RegisterType((*Target)(nil), "pb.Target")
}

func init() { proto.RegisterFile("doneself.protobuf", fileDescriptor_a854b94b567af670) }

var fileDescriptor_a854b94b567af670 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xd9, 0x6d, 0x5d, 0xdb, 0xf1, 0x0f, 0x38, 0x16, 0x0d, 0x8a, 0x50, 0x16, 0x0f, 0x3d,
	0xed, 0xa1, 0x5e, 0xbd, 0x14, 0xbc, 0x78, 0xe8, 0xc1, 0xe8, 0x51, 0x28, 0x8d, 0x99, 0x96, 0x40,
	0xdc, 0xc4, 0x9d, 0x14, 0x6c, 0x3f, 0xbd, 0x24, 0xa9, 0xa0, 0xe8, 0xf1, 0xfd, 0xde, 0x90, 0xf7,
	0xf2, 0xe0, 0x4c, 0xbb, 0x96, 0x98, 0xec, 0xaa, 0xf1, 0x9d, 0x0b, 0x4e, 0x6d, 0x56, 0x58, 0x7a,
	0x55, 0x3f, 0xc1, 0xf9, 0xcc, 0xda, 0xf9, 0xf6, 0x65, 0xd9, 0xad, 0x29, 0xb0, 0xa4, 0x8f, 0x0d,
	0x71, 0xc0, 0x1b, 0x00, 0xbf, 0x5c, 0xd3, 0xc2, 0xb4, 0x9a, 0x3e, 0x45, 0x31, 0x2e, 0x26, 0x27,
	0x72, 0x18, 0xc9, 0x63, 0x04, 0x78, 0x0d, 0x49, 0x2c, 0xd8, 0xec, 0x48, 0x94, 0xc9, 0x1d, 0x44,
	0xf0, 0x6c, 0x76, 0x54, 0xdf, 0xc3, 0xe8, 0xf7, 0x93, 0xec, 0x5d, 0xcb, 0x84, 0xb7, 0x70, 0x18,
	0x32, 0x12, 0xc5, 0xb8, 0x37, 0x39, 0x9a, 0x42, 0xe3, 0x55, 0x93, 0xaf, 0xe4, 0xb7, 0x55, 0xbf,
	0x42, 0x95, 0x11, 0x9e, 0x42, 0x69, 0x74, 0xca, 0xee, 0xcb, 0xd2, 0x68, 0x1c, 0xc1, 0x41, 0x30,
	0xc1, 0xe6, 0xc0, 0xa1, 0xcc, 0x22, 0x52, 0x7e, 0x73, 0x1d, 0x89, 0x5e, 0xaa, 0x91, 0x05, 0x5e,
	0x40, 0xc5, 0xdb, 0x77, 0xe5, 0xac, 0xe8, 0xa7, 0xe3, 0xbd, 0x9a, 0xce, 0x61, 0xf0, 0xb0, 0xdf,
	0x01, 0x67, 0x70, 0xfc, 0xb3, 0x27, 0x5e, 0xc6, 0x3a, 0xff, 0x8c, 0x71, 0x25, 0xfe, 0x1a, 0xf9,
	0x4b, 0xaa, 0x4a, 0x5b, 0xde, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x3c, 0x00, 0xa4, 0x5d,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DoneselfClient is the client API for Doneself service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DoneselfClient interface {
	AllMyTargets(ctx context.Context, in *AllMyTargetsRequest, opts ...grpc.CallOption) (*AllMyTargetsResponse, error)
}

type doneselfClient struct {
	cc *grpc.ClientConn
}

func NewDoneselfClient(cc *grpc.ClientConn) DoneselfClient {
	return &doneselfClient{cc}
}

func (c *doneselfClient) AllMyTargets(ctx context.Context, in *AllMyTargetsRequest, opts ...grpc.CallOption) (*AllMyTargetsResponse, error) {
	out := new(AllMyTargetsResponse)
	err := c.cc.Invoke(ctx, "/pb.Doneself/AllMyTargets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DoneselfServer is the server API for Doneself service.
type DoneselfServer interface {
	AllMyTargets(context.Context, *AllMyTargetsRequest) (*AllMyTargetsResponse, error)
}

func RegisterDoneselfServer(s *grpc.Server, srv DoneselfServer) {
	s.RegisterService(&_Doneself_serviceDesc, srv)
}

func _Doneself_AllMyTargets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllMyTargetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DoneselfServer).AllMyTargets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Doneself/AllMyTargets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DoneselfServer).AllMyTargets(ctx, req.(*AllMyTargetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Doneself_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Doneself",
	HandlerType: (*DoneselfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AllMyTargets",
			Handler:    _Doneself_AllMyTargets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "doneself.protobuf",
}
